version: '3.8'

services:
  api:
    container_name: rag-testcase-generator-JJ
    build: .
    ports:
      - "10500:10500"
    volumes:
      # Mount outputs to persist results
      - ./runs:/app/runs
      - ./src/files:/app/src/files
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
